-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here

vim.keymap.set("n", "<C-h>", "<Cmd>TmuxNavigateLeft<CR>", { silent = true })
vim.keymap.set("n", "<C-j>", "<Cmd>TmuxNavigateDown<CR>", { silent = true })
vim.keymap.set("n", "<C-k>", "<Cmd>TmuxNavigateUp<CR>", { silent = true })
vim.keymap.set("n", "<C-l>", "<Cmd>TmuxNavigateRight<CR>", { silent = true })

vim.keymap.set("n", "<C-n>", "<Cmd>BufferLineCycleNext<CR>", { silent = true })
vim.keymap.set("n", "<C-p>", "<Cmd>BufferLineCyclePrev<CR>", { silent = true })

vim.keymap.set("n", "<leader>b1", function()
  require("bufferline").go_to(1, true)
end, { desc = "Go to Buffer 1", silent = true })
vim.keymap.set("n", "<leader>b2", function()
  require("bufferline").go_to(2, true)
end, { desc = "Go to Buffer 2", silent = true })
vim.keymap.set("n", "<leader>b3", function()
  require("bufferline").go_to(3, true)
end, { desc = "Go to Buffer 3", silent = true })
vim.keymap.set("n", "<leader>b4", function()
  require("bufferline").go_to(4, true)
end, { desc = "Go to Buffer 4", silent = true })
vim.keymap.set("n", "<leader>b5", function()
  require("bufferline").go_to(5, true)
end, { desc = "Go to Buffer 5", silent = true })
vim.keymap.set("n", "<leader>b6", function()
  require("bufferline").go_to(6, true)
end, { desc = "Go to Buffer 6", silent = true })
vim.keymap.set("n", "<leader>b7", function()
  require("bufferline").go_to(7, true)
end, { desc = "Go to Buffer 7", silent = true })
vim.keymap.set("n", "<leader>b8", function()
  require("bufferline").go_to(8, true)
end, { desc = "Go to Buffer 8", silent = true })
vim.keymap.set("n", "<leader>b9", function()
  require("bufferline").go_to(9, true)
end, { desc = "Go to Buffer 9", silent = true })
