save-position-on-quit

hwdec=auto

sub-auto=fuzzy
sub-scale=0.7
sub-font='Helvectica Neue'
sub-ass-override=force

# 1. The "Core" density (provides opacity closer to the text)
sub-border-size=1.2
sub-border-color="#000000"

# 2. The "Feather" (provides the soft outer look)
sub-shadow-offset=0.8
sub-shadow-color="#000000"
sub-blur=1.8                  # Higher value = softer YouTube-style glow

script-opts=ytdl_hook-ytdl_path=yt-dlp
ytdl-format=bestvideo[height<=?1080][fps<=?60]+bestaudio
ytdl-raw-options=sub-format=en,write-srt=
ytdl-raw-options-append=no-check-certificates=
